# Storage - mongo-pvc (How do you want it)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessMode: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# Storage - mongo-pvc (How do you want it implemented)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
