apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-project
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:

  - host: www.chichieo.live
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fleetman-webapp
            port:
              number: 80

  tls:
    - hosts:
        - www.chichieo.live